apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-d-b
  labels:
    app: chart-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chart-b
  template:
    metadata:
      labels:
        app: chart-b
    spec:
      containers:
      - name: chart
        image: chartimage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 0.1
            memory: "200Mi"
